name: seam_carver_dart
description: Library to seam carve images
version: 1.0.0
repository: https://github.com/ArtAhmetaj/seam_carver_dart

environment:
  sdk: ^3.2.5

# Add regular dependencies here.
dependencies:
  image: ^4.2.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
